### ISSUE TITLE
logo from @nsoch painting

### ISSUE THREAD

**Issue by vsoch** [vsoch/opensource-art#1]
@nsoch do you want to take a photograph of a circle texture from one of your paintings, for use for the logo? If we use the concentric circle I will want to reach out to the creator (of the algorithm) to get his permission - since this is our project it might be more appropriate for the logo to be created by you.

**Comment by nsoch** [comment]
I agree. Am in car right now but this eve when I return home or when I get to ArtSpace will send logo candidate

**Comment by vsoch** [comment]
sounds good!

**Comment by vsoch** [comment]
Closing issue, very happy with current logo :)

**Comment by nsoch** [comment]
👍🏻
